version: '3.7'

services: 
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      # TODO アプリ名に応じてDB名変更
      MYSQL_DATABASE: app_development
      MYSQL_PASSWORD: password
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-db:/var/lib/mysql
  api:
    tty: true
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app
    command: |
      bash -c "
      rm -f /app/tmp/pids/server.pid &&
      ./scripts/migrate_by_ridgepole.sh &&
      bundle exec rails s -p ${API_PORT} -b '0.0.0.0'
      "
  front: 
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
volumes:
  mysql-db:
    driver: local